
#Postgressql
#http://stackoverflow.com/questions/6710654/change-from-sqlite-to-postgresql-in-a-fresh-rails-project
#https://medium.com/@helenflam/how-to-change-your-rails-app-database-from-sqlite-to-postgresql-before-deploying-to-heroku-ae2acc25c7ac#.3c73mjcgf
#
#development:
#  adapter: postgresql
#  encoding: unicode
#  database: project_development
#  pool: 5
#  timeout: 5000
#  username: 
#  password:
#  socket: /tmp/.s.PGSQL.5432 #/var/pgsql_socket
#
#test: &TEST
#  adapter: postgresql
#  encoding: unicode
#  database: project_test
#  pool: 5
#  timeout: 5000
#  username: 
#  password:
#
#production:
#  adapter: postgresql
#  encoding: unicode
#  database: project_production
#  pool: 5
#  timeout: 5000
#  username: 
#  password:
#
#----------------------------------------------------------------------------
# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
